// Auth pages
export { default as LoginPage } from './authPages/LoginPage'
export { default as ForgotPassword } from './authPages/ForgotPassword'
export { default as ResetPassword } from './authPages/ResetPassword'
export { default as ProfilePage } from './authPages/ProfilePage'
export { default as SignupPage } from './authPages/SignupPage'

// Admin pages
export { default as AdminDashboard } from './adminPages/AdminDashboard'
export { default as AdminUsersPage } from './adminPages/AdminUsersPage'
export { default as PropertyPage } from './adminPages/PropertyPage'
export { default as PropertyFloorsPage } from './adminPages/PropertyFloorsPage'
export { default as FloorPage } from './adminPages/FloorPage'
export { default as FloorLocalsPage } from './adminPages/FloorLocalsPage'
export { default as LocalPage } from './adminPages/LocalPage'
export { default as TenantPage } from './adminPages/TenantPage'
export { default as LeasePage } from './adminPages/LeasePage'
export { default as PaymentModePage } from './adminPages/PaymentModePage'
export { default as PaymentPage } from './adminPages/PaymentPage'
export { default as ExpensePage } from './adminPages/ExpensePage'
export { default as StaffPage } from './adminPages/StaffPage'
export { default as Documents } from './adminPages/Documents'
export { default as Reports } from './adminPages/ReportsPage'
export { default as AdminSettingsPage } from './adminPages/SettingsPage'

// Manager pages
export { default as ManagerDashboard } from './managerPages/ManagerDashboard'
export { default as ManagerPropertyPage } from './managerPages/PropertyPage'
export { default as ManagerLocalPage } from './managerPages/LocalPage'
export { default as ManagerTenantPage } from './managerPages/TenantPage'
export { default as ManagerLeasePage } from './managerPages/LeasePage'
export { default as ManagerPaymentPage } from './managerPages/PaymentPage'
export { default as ManagerExpensePage } from './managerPages/ExpensePage'
export { default as ManagerReportsPage } from './managerPages/Reports'
export { default as ManagerFloorPage } from './managerPages/FloorPage'
export { default as ManagerPropertyFloorsPage } from './managerPages/PropertyFloorsPage'
export { default as ManagerFloorLocalsPage } from './managerPages/FloorLocalsPage'

// General pages
export { default as NotFoundPage } from './NotFoundPage'
